name: Common
on:
  workflow_call:
    inputs:
      type:
        required: true
        type: string
      is-snapshot:
        required: false
        type: boolean
        default: true
      change-log:
        required: false
        type: string
      release-tag:
        required: false
        type: string
        default: ''

jobs:
  build-common:
    name: Build Common
    runs-on: ubuntu-latest
    environment: Build
    steps:
      -
        name: Checkout
        uses: actions/checkout@v7
      -
        name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'oracle'
          java-version: '25'
          cache: 'gradle'
      -
        name: Build
        id: build
        env:
          IS_SNAPSHOT: ${{ inputs.is-snapshot }}
        run: |
          ./gradlew clean test shadowJar --info --stacktrace
      -
        name: Publish Modrinth
        if: ${{ !inputs.is-snapshot }}
        env:
          IS_SNAPSHOT: ${{ inputs.is-snapshot }}
          CHANGE_LOG: ${{ inputs.change-log }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        run: |
          ./gradlew modrinth modrinthSyncBody --info --stacktrace
      -
        name: Publish GitHub Release
        if: ${{ !cancelled() && steps.build.outcome == 'success' && !inputs.is-snapshot && inputs.release-tag != '' }}
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ inputs.release-tag }}
          files: build/libs/*.jar
          fail_on_unmatched_files: true
      -
        name: Upload workflow artifact
        if: ${{ !cancelled() && steps.build.outcome == 'success' }}
        uses: actions/upload-artifact@v7
        with:
          name: I18nAutoUpdateMod-${{ inputs.type }}-${{ github.run_number }}
          path: build/libs
